---
# List handlers for Apache2

- name: Restart nginx
  service: name=nginx state=restarted

- name: Graceful apache
  service: name=nginx state=graceful

- name: Start mariadb
  service: name=mariadb state=started

- name: Stop mariadb
  service: name=mariadb state=stoped

- name: Restart mariadb
  service: name=mariadb state=restarted
