---

- name: HHVM | Add repository
  apt_key: url=http://dl.hhvm.com/conf/hhvm.gpg.key state=present

- name: HHVM | Add source sources
  apt_repository: repo='deb http://dl.hhvm.com/ubuntu saucy main' update_cache=yes

- name: HHVM | Install Packages
  apt: pkg=hhvm state=installed