---

- name: Package | Install lists packages
  dnf: name={{ item }} state=installed
  with_items:
    - bash-completion
    - openssh-server
    - vim
    - git
    - NetworkManager-tui
    - unar
    - htop
    - tree
    - dstat
    - screen
    - curl
    - wget
    - ccze
    - tmux
    - terminator
    - tig
    - unzip
    - gnome-tweak-tool
    - python-pip



