---

- name: Package | Install lists packages
  dnf: name={{ item }} state=installed
  with_items:
    - bash-completion
    - openssh-server
    - vim
    - git
    - NetworkManager-tui
    - unar
    - htop
    - tree
    - dstat
    - screen
    - curl
    - wget
    - ccze
    - tmux
    - terminator
    - tig
    - unzip
    - libselinux-python
    - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-23.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-23.noarch.rpm
    - gnome-tweak-tool

