---

# Install custom vim
- name: VIM | Clone vim config
  become: false
  git: repo=https://github.com/lesmyrmidons/vim-config.git
       dest=/home/{{ user }}/.vim-config
       update=yes
       accept_hostkey=yes
  ignore_errors: true

- name: VIM | Created symlink (vimrc)
  become: false
  file: src=/home/{{ user }}/.vim-config/vimrc dest=/home/{{ user }}/.vimrc owner={{ user }} group={{ user }} state=link

- name: VIM | Created symlink (.vim/)
  become: false
  file: src=/home/{{ user }}/.vim-config/vim dest=/home/{{ user }}/.vim owner={{ user }} group={{ user }} state=link
